# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Distribute app"
  lane :distribute do
    build_android_app(
      task: "assemble",
      build_type: "Release"
    ) # builtin fastlane action
    firebase_app_distribution(
      # app: "1:466933397959:android:b68b179ebf3c0f7ea041e2",
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_APP_TOKEN"],
      testers: "craig", # group created in Firebase Add Distribution
      release_notes: "First trial of an actual app release",
      # debug: true,
      android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab"
      android_artifact_type: "AAB"
    )
  end
end
