# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Distribute app"
  lane :distribute do
    build_android_app(
      task: "assemble",
      build_type: "Release",
      properties: {
        "android.injected.version.code" => 101,
        "android.injected.version.name" => "1.0.1",
      }
    ) # builtin fastlane action
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_APP_TOKEN"],
      testers: "craig", # group created in Firebase Add Distribution
      release_notes: "Does this work?",

      # debug: true,
      # The below two lines referencing AAB can only be used if you link the Google Play account to the app
      # android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab",
      # android_artifact_type: "AAB"
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
      android_artifact_type: "APK"
    )
  end
end
